INSERT INTO ROLE (NOME_ROLE) VALUES('ROLE_ADMIN');
INSERT INTO ROLE (NOME_ROLE) VALUES('ROLE_COMUM');

INSERT INTO USUARIO (LOGIN,SENHA) VALUES('admin','$2a$10$.y6Jw.mjYAQw5SqOGtBjcO4rb3qDsvx5OwRd9qoQ3Yrwxi7fAMR.W');
INSERT INTO USUARIO (LOGIN,SENHA) VALUES('comum','$2a$10$.y6Jw.mjYAQw5SqOGtBjcO4rb3qDsvx5OwRd9qoQ3Yrwxi7fAMR.W');

INSERT INTO USUARIOS_ROLES (USUARIO_ID, ROLE_ID) VALUES('admin','ROLE_ADMIN');
INSERT INTO USUARIOS_ROLES (USUARIO_ID, ROLE_ID) VALUES('comum','ROLE_COMUM');
